import type { Metadata } from "next";
import { MainNav } from "../components/layout/main-nav";
import { Search } from "../components/layout/search";
import { UserNav } from "../components/layout/user-nav";
import TeamSwitcher from "../components/layout/team-switcher";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <main>
      <div className="hidden flex-col md:flex">
        <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <TeamSwitcher />
            <MainNav className="mx-6" />
            <div className="ml-auto flex items-center space-x-4">
              <Search />
              <UserNav />
            </div>
          </div>
        </div>
        <div className="flex-1 space-y-4 p-8 pt-6">
        {children}
        </div>
      </div>
        </main>
    </html>
  );
}
